/*
 * I2C_Scanner.ino — Automato Brain Board V2.0
 *
 * Generic I2C bus scanner with comprehensive device database.
 * Scans all 127 possible I2C addresses and identifies any device
 * found using a database sourced from https://i2cdevices.org
 * (MIT License — database auto-generated by i2cdevices.org)
 *
 * Brain Board I2C pins: SDA = IO6, SCL = IO7
 *
 * HOW TO USE:
 *   1. Flash to Brain Board with any Qwiic devices connected
 *   2. Open Serial Monitor at 115200 baud
 *   3. Press RESET to scan
 *   4. All found devices printed with part number and description
 *
 * Multiple matches at the same address are normal — many devices
 * share addresses. Use context to identify which one you have.
 *
 * DATABASE SOURCE: https://i2cdevices.org (updated 2026-03-17)
 * To refresh: download https://i2cdevices.org/devices.json
 */

#include <Wire.h>

struct I2CDevice {
  const char* part;
  const char* description;
  const uint8_t addresses[17];
};

const I2CDevice KNOWN_DEVICES[] = {
  { "47L04/47C04",  "I2C Serial EERAM - Control register",              { 0x18,0x1A,0x1C,0x1E,0 } },
  { "47L04/47C04",  "I2C Serial EERAM - SRAM with EEPROM backup",       { 0x56,0x50,0x52,0x54,0 } },
  { "AD5243",       "Dual 256-Position Digital Potentiometer",           { 0x2F,0 } },
  { "ADS1015",      "4-channel 12-bit ADC",                              { 0x4B,0x49,0x4A,0x48,0 } },
  { "ADS1115",      "4-channel 16-bit ADC",                              { 0x4B,0x49,0x4A,0x48,0 } },
  { "ADS7828",      "12-Bit 8-Channel ADC",                              { 0x4B,0x49,0x4A,0x48,0 } },
  { "ADXL345",      "3-axis accelerometer",                              { 0x1D,0x53,0 } },
  { "AHT10",        "Humidity and Temperature sensor",                   { 0x38,0 } },
  { "AHT20",        "Humidity and Temperature Sensor",                   { 0x38,0 } },
  { "AK8975",       "3-axis magnetometer",                               { 0x0E,0x0F,0x0C,0x0D,0 } },
  { "AM2315",       "Humidity/Temp sensor",                              { 0x5C,0 } },
  { "AM2320",       "Digital Temperature and Humidity Sensor",           { 0x5C,0 } },
  { "AMG8833",      "IR Thermal Camera Breakout",                        { 0x68,0x69,0 } },
  { "APDS-9250",    "Digital RGB, IR and Ambient Light Sensor",          { 0x52,0 } },
  { "APDS-9960",    "IR/Color/Proximity Sensor",                         { 0x39,0 } },
  { "AS7262",       "6-channel visible spectral ID device",              { 0x49,0 } },
  { "AT24C02N",     "Two-wire Serial EEPROM 2K",                         { 0x55,0x56,0x57,0x50,0x51,0x52,0x54,0x53,0 } },
  { "AT24C64",      "Serial EEPROM 64K",                                 { 0x55,0x56,0x57,0x50,0x51,0x52,0x54,0x53,0 } },
  { "ATECC508A",    "CryptoAuthentication Device",                       { 0x60,0 } },
  { "ATECC608A",    "CryptoAuthentication Device",                       { 0x60,0 } },
  { "BH1750FVI",    "Digital 16bit Ambient Light Sensor",                { 0x5C,0x23,0 } },
  { "BME280",       "Temp/Barometric/Humidity",                          { 0x76,0x77,0 } },
  { "BME680",       "Gas/Pressure/Temp/Humidity sensor",                 { 0x76,0x77,0 } },
  { "BME688",       "Gas/Pressure/Temp/Humidity sensor with AI",         { 0x76,0x77,0 } },
  { "BMP085",       "Temp/Barometric (obsolete)",                        { 0x77,0 } },
  { "BMP180",       "Temp/Barometric",                                   { 0x77,0 } },
  { "BMP280",       "Temp/Barometric",                                   { 0x76,0x77,0 } },
  { "BNO055",       "Absolute Orientation Sensor (9-DOF IMU)",           { 0x28,0x29,0 } },
  { "BQ32000",      "Real-Time Clock (RTC)",                             { 0x68,0 } },
  { "CAP1188",      "8-channel Capacitive Touch",                        { 0x28,0x29,0x2D,0x2B,0x2A,0x2C,0 } },
  { "CCS811",       "VOC/eCO2 Air Quality Sensor",                       { 0x5B,0x5A,0 } },
  { "Chirp!",       "Soil Water sensor",                                 { 0x20,0 } },
  { "COM-15093",    "SparkFun Qwiic Single Relay",                       { 0x18,0x19,0 } },
  { "DRV2605",      "Haptic Motor Driver",                               { 0x5A,0 } },
  { "DS1307",       "64x8 Serial Real-Time Clock",                       { 0x68,0 } },
  { "DS3231",       "Extremely Accurate RTC/TCXO/Crystal",               { 0x68,0 } },
  { "DS3502",       "High-Voltage NV I2C Potentiometer",                 { 0x28,0x29,0x2B,0x2A,0 } },
  { "EMC2101",      "SMBus Fan Control + Temperature Monitor",           { 0x4C,0 } },
  { "FS3000",       "Air Velocity Sensor 3.3V",                          { 0x28,0 } },
  { "FXAS21002",    "3-axis gyroscope",                                  { 0x20,0x21,0 } },
  { "FXOS8700",     "6-axis accelerometer + magnetometer",               { 0x1F,0x1C,0x1D,0x1E,0 } },
  { "HDC1008",      "Digital Humidity + Temperature Sensor",             { 0x43,0x42,0 } },
  { "HDC1080",      "Low Power Digital Humidity + Temperature Sensor",   { 0x40,0 } },
  { "HIH6130",      "HumidIcon Humidity/Temp Sensor",                    { 0x27,0 } },
  { "HMC5883",      "3-Axis Digital Compass/Magnetometer",               { 0x1E,0 } },
  { "HT16K33",      "LED Matrix Driver",                                 { 0x70,0x71,0x72,0x73,0x74,0x75,0x76,0x77,0 } },
  { "HTS221",       "Relative humidity and temperature sensor",          { 0x5F,0 } },
  { "HTU21D-F",     "Humidity/Temp Sensor",                              { 0x40,0 } },
  { "HTU31D",       "Digital Relative Humidity & Temperature Sensor",    { 0x40,0x41,0 } },
  { "ICM-20948",    "9-Axis IMU (Gyro + Accel + Mag)",                   { 0x68,0x69,0 } },
  { "INA219",       "26V Bi-Directional Current/Power Monitor",          { 0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0 } },
  { "INA260",       "Precision Current and Power Monitor",               { 0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0 } },
  { "ITG3200",      "Gyro",                                              { 0x68,0x69,0 } },
  { "L3GD20H",      "Gyroscope",                                         { 0x6A,0x6B,0 } },
  { "LC709203F",    "LiB Gauge Battery Fuel Gauge",                      { 0x11,0 } },
  { "LIS3DH",       "3-axis accelerometer",                              { 0x18,0x19,0 } },
  { "LM75b",        "Digital temperature sensor",                        { 0x48,0x49,0x4A,0x4B,0x4C,0x4D,0x4E,0x4F,0 } },
  { "LPS22HB",      "MEMS nano pressure sensor",                         { 0x2E,0 } },
  { "LSM303",       "Triple-axis Accelerometer + Magnetometer",          { 0x18,0x19,0x1E,0 } },
  { "MAG3110",      "3-Axis Magnetometer",                               { 0x0E,0 } },
  { "MAX17048",     "1-Cell/2-Cell Fuel Gauge",                          { 0x36,0 } },
  { "MAX30101",     "Pulse Oximeter and Heart-Rate Sensor",              { 0x55,0 } },
  { "MAX44009",     "Ambient Light Sensor with ADC",                     { 0x4A,0x4B,0 } },
  { "MCP23008",     "8-Bit I2C GPIO Expander",                           { 0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0 } },
  { "MCP23017",     "16-Bit I2C GPIO Expander",                          { 0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0 } },
  { "MCP4725A0",    "12-bit DAC",                                        { 0x60,0x61,0 } },
  { "MCP9808",      "+-0.5C Accuracy Digital Temperature Sensor",        { 0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,0 } },
  { "MLX90614",     "IR temperature sensor",                             { 0x5A,0 } },
  { "MLX90632",     "FIR temperature sensor",                            { 0x3A,0 } },
  { "MLX90640",     "32x24 Far-IR Thermal Sensor Array",                 { 0x33,0 } },
  { "MMA845x",      "3-axis 14-bit digital accelerometer",               { 0x1C,0x1D,0 } },
  { "MPL3115A2",    "Barometric Pressure sensor",                        { 0x60,0 } },
  { "MPR121",       "12-point capacitive touch sensor",                  { 0x5A,0x5B,0x5C,0x5D,0 } },
  { "MPU6050",      "6-Axis Gyro + Accelerometer IMU",                   { 0x68,0x69,0 } },
  { "MPU-9250",     "9-DOF Gyro + Accelerometer + Magnetometer IMU",     { 0x68,0x69,0 } },
  { "MS5607",       "Barometric Pressure sensor",                        { 0x76,0x77,0 } },
  { "MS5611",       "Barometric Pressure sensor",                        { 0x76,0x77,0 } },
  { "PCA6408A",     "8-bit I2C I/O Expander",                            { 0x20,0x21,0 } },
  { "PCA9536",      "4-bit I2C I/O Expander",                            { 0x41,0 } },
  { "PCA9539",      "16-bit I/O Expander with interrupt",                { 0x74,0x75,0x76,0x77,0 } },
  { "PCA9685",      "16-channel PWM/Servo Driver",                       { 0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0 } },
  { "PCF8523",      "Real-Time Clock",                                   { 0x68,0 } },
  { "PCF8563",      "Real-time clock/calendar",                          { 0x51,0 } },
  { "PCF8574",      "Remote 8-Bit I2C I/O Expander",                     { 0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0 } },
  { "PCF8574AP",    "I2C-bus to parallel port expander",                 { 0x38,0x39,0x3A,0x3B,0x3C,0x3D,0x3E,0x3F,0 } },
  { "PCF8575",      "Remote 16-Bit I2C I/O Expander",                    { 0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0 } },
  { "PMSA003I",     "Digital Particulate Concentration Sensor",          { 0x12,0 } },
  { "PN532",        "NFC/RFID Reader",                                   { 0x48,0 } },
  { "SCD30",        "CO2, Humidity, and Temperature Sensor",             { 0x61,0 } },
  { "SCD40",        "CO2 Sensor (up to 2000ppm)",                        { 0x62,0 } },
  { "SCD41",        "CO2 Sensor",                                        { 0x62,0 } },
  { "SFA30",        "Formaldehyde Sensor (HVAC/IAQ)",                    { 0x5D,0 } },
  { "SGP30",        "Gas/VOC Sensor",                                    { 0x58,0 } },
  { "SGP40",        "Indoor Air Quality VOC Sensor",                     { 0x59,0 } },
  { "SH1106",       "132x64 OLED Display Driver",                        { 0x3C,0x3D,0 } },
  { "SHT31",        "Humidity/Temp sensor",                              { 0x44,0x45,0 } },
  { "SHTC3",        "Humidity & Temperature Sensor",                     { 0x70,0 } },
  { "SI7021",       "Humidity/Temp sensor",                              { 0x40,0 } },
  { "SPL06-007",    "Digital Temperature/Pressure Sensor",               { 0x76,0x77,0 } },
  { "SPS30",        "Particulate Matter Sensor for Air Quality",         { 0x69,0 } },
  { "SSD1305",      "132x64 OLED Display Driver",                        { 0x3C,0x3D,0 } },
  { "SSD1306",      "128x64 OLED Display Driver",                        { 0x3C,0x3D,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=0,A1=0,A2=0)",         { 0x20,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=1,A1=0,A2=0)",         { 0x21,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=0,A1=1,A2=0)",         { 0x22,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=1,A1=1,A2=0)",         { 0x23,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=0,A1=0,A2=1)",         { 0x24,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=1,A1=0,A2=1)",         { 0x25,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=0,A1=1,A2=1)",         { 0x26,0 } },
  { "TCA9534",      "8-bit I2C GPIO Expander (A0=1,A1=1,A2=1)",         { 0x27,0 } },
  { "TCA9548",      "1-to-8 I2C Multiplexer",                           { 0x70,0x71,0x72,0x73,0x74,0x75,0x76,0x77,0 } },
  { "TCA9548A",     "Low-Voltage 8-Channel I2C Switch with Reset",       { 0x70,0x71,0x72,0x73,0x74,0x75,0x76,0x77,0 } },
  { "TCA9554",      "8-Bit I2C I/O Expander",                            { 0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0 } },
  { "TCS34725",     "RGB Color Sensor",                                  { 0x29,0 } },
  { "TMP102",       "Temperature Sensor",                                { 0x48,0x49,0x4A,0x4B,0 } },
  { "TMP006",       "Infrared Thermopile Sensor",                        { 0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0 } },
  { "TMP007",       "IR Temperature Sensor",                             { 0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0 } },
  { "TPA2016",      "Stereo Class-D Audio Amplifier",                    { 0x58,0 } },
  { "TSL2561",      "Digital Luminosity/Lux/Light Sensor",               { 0x29,0x39,0x49,0 } },
  { "TSL2591",      "High Dynamic Range Digital Light Sensor",           { 0x29,0 } },
  { "VCNL4200",     "Long Distance Proximity and Ambient Light Sensor",  { 0x51,0 } },
  { "VEML6070",     "UVA Light Sensor",                                  { 0x38,0x39,0 } },
  { "VEML6075",     "UVA and UVB Light Sensor",                          { 0x10,0 } },
  { "VEML7700",     "High Accuracy Ambient Light Sensor",                { 0x10,0 } },
  { "VL53L0x",      "Time Of Flight Distance Sensor",                    { 0x29,0 } },
  { "VL6180X",      "Time Of Flight Distance Sensor",                    { 0x29,0 } },
  { "ZMOD4410",     "Indoor Air Quality (IAQ) and TVOC Sensor",          { 0x32,0 } },
  { "ZMOD4510",     "Gas Sensor for O3 and NO2",                         { 0x33,0 } },
};

const uint8_t NUM_KNOWN_DEVICES = sizeof(KNOWN_DEVICES) / sizeof(I2CDevice);

void printMatchingDevices(uint8_t addr) {
  for (uint8_t i = 0; i < NUM_KNOWN_DEVICES; i++) {
    const uint8_t* addrs = KNOWN_DEVICES[i].addresses;
    for (uint8_t j = 0; addrs[j] != 0; j++) {
      if (addrs[j] == addr) {
        Serial.printf("           %-14s %s\n",
                      KNOWN_DEVICES[i].part,
                      KNOWN_DEVICES[i].description);
        break;
      }
    }
  }
}

bool isKnownDevice(uint8_t addr) {
  for (uint8_t i = 0; i < NUM_KNOWN_DEVICES; i++) {
    const uint8_t* addrs = KNOWN_DEVICES[i].addresses;
    for (uint8_t j = 0; addrs[j] != 0; j++) {
      if (addrs[j] == addr) return true;
    }
  }
  return false;
}

void setup() {
  Serial.begin(115200);
  delay(1000);

  Wire.begin(6, 7);  // Brain Board V2.0: SDA=IO6, SCL=IO7

  Serial.println("\n=== Automato Brain Board I2C Scanner ===");
  Serial.printf("Database: %d known devices (i2cdevices.org)\n\n", NUM_KNOWN_DEVICES);
  Serial.println("Scanning...\n");

  uint8_t count = 0;

  for (uint8_t addr = 1; addr < 127; addr++) {
    Wire.beginTransmission(addr);
    uint8_t error = Wire.endTransmission();

    if (error == 0) {
      Serial.printf("  [0x%02X] Device found", addr);
      if (!isKnownDevice(addr)) {
        Serial.println(" — Unknown device");
      } else {
        Serial.println(" — possible matches:");
        printMatchingDevices(addr);
      }
      count++;
    } else if (error == 4) {
      Serial.printf("  [0x%02X] Unknown error\n", addr);
    }
  }

  Serial.println();
  Serial.printf("Scan complete. %d device(s) found.\n", count);
  if (count == 0) Serial.println("Check wiring — SDA=IO6, SCL=IO7");
  Serial.println("Press RESET to scan again.");
}

void loop() {}
